# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mgrandia <mgrandia@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/28 12:26:00 by mgrandia          #+#    #+#              #
#    Updated: 2024/12/28 13:16:52 by mgrandia         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

CC = cc

FLAGS = -Wall -Wextra -Werror

FILES= ft_display_file.c

all: 
	$(CC) $(FLAGS) -o $(NAME) $(FILES)

clean:
	rm -f *.o

fclean: clean
	rm -rf $(NAME)
	
